import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/navbar';
import { ReduxProvider } from './provider';
import userLoginStatus from './../firebase/firebase';
// import { login } from '../../firebase/firebase';
import { AuthContextProvider } from './contextProvider';
import { Loading } from './loading';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'FundingApp',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AuthContextProvider>
					<ReduxProvider>
						<Suspense fallback={<Loading />}>{children}</Suspense>
					</ReduxProvider>
				</AuthContextProvider>
			</body>
		</html>
	);
}
