import './globals.css';
import { Poppins } from 'next/font/google';
import { ReduxProvider } from './provider';
import Loading from './loading';
import { Suspense } from 'react';

const poppins = Poppins({
	subsets: ['latin'],
	weight: '400',
});

export const metadata = {
	title: 'FundingApp',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<ReduxProvider>
					<Suspense fallback={<Loading />}>{children}</Suspense>
				</ReduxProvider>
			</body>
		</html>
	);
}
