import './globals.css';
import { Poppins } from 'next/font/google';
import { ReduxProvider } from './provider';
import Loading from './loading';
import { Suspense } from 'react';
import { useLocale, NextIntlClientProvider, useMessages } from 'next-intl';
import { notFound } from 'next/navigation';

const poppins = Poppins({
	subsets: ['latin'],
	weight: '400',
});

export const metadata = {
	title: 'FundingApp',
	description: 'Generated by create next app',
};

export default function RootLayout({ children, params }) {
	const locale = useLocale();

	const messages = useMessages();

	// Show a 404 error if the user requests an unknown locale
	if (params.locale !== locale) {
		notFound();
	}
	return (
		<html lang={locale}>
			<body className={poppins.className}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<ReduxProvider>
						<Suspense fallback={<Loading />}>{children}</Suspense>
					</ReduxProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
